# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:6.4.2

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
#RUN kibana-plugin install x-pack
#RUN kibana-plugin install ingest-geoip
#RUN kibana-plugin install ingest-user-agent
